DROP TABLE IF EXISTS domicilios;
CREATE TABLE domicilios(ID INT AUTO_INCREMENT PRIMARY KEY,
CALLE varchar(200) NOT NULL,
NUMERO INT NOT NULL,
LOCALIDAD varchar(200) NOT NULL,
PROVINCIA varchar(200) NOT NULL);

DROP TABLE IF EXISTS pacientes;
CREATE TABLE pacientes(ID INT AUTO_INCREMENT PRIMARY KEY,
APELLIDO varchar(200) NOT NULL,
NOMBRE varchar(200) NOT NULL,
DNI varchar(200) NOT NULL,
FECHA_INGRESO DATE NOT NULL,
DOMICILIO_ID INT NOT NULL);

INSERT INTO domicilios(CALLE, NUMERO, LOCALIDAD, PROVINCIA) VALUES ('Calle Falsa', 123, 'Ciudad Falsa', 'Provincia Falsa');
INSERT INTO domicilios(CALLE, NUMERO, LOCALIDAD, PROVINCIA) VALUES ('Otra Calle Falsa', 444, 'Otra Ciudad Falsa', 'Otra Provincia Falsa');

INSERT INTO pacientes(APELLIDO, NOMBRE, DNI, FECHA_INGRESO, DOMICILIO_ID) VALUES ('Apellido Falsa', 'Nombre Falsa', 12345678, '2021-01-09', 1);
INSERT INTO pacientes(APELLIDO, NOMBRE, DNI, FECHA_INGRESO, DOMICILIO_ID) VALUES ('Otro ApellidoFalsa', 'Otro NombreFalsa', 87654321, '2019-07-01', 2);
